export const names = [
    "Al Bino",
    "Al Dente",
    "Al K. Seltzer",
    "Amanda Lynn",
    "Anita Bathe",
    "Anita Job",
    "Anna Conda",
    "Anna Graham",
    "Anna Prentice",
    "Anna Sasin",
    "Anna Sthesia",
    "Anna Swayze",
    "Anna T. Raction",
    "Anna W. Reck",
    "B.A. Ware",
    "Barry Cade",
    "Bea Minor",
    "Dee Major",
    "Ben Dover",
    "Bill Ding",
    "Bill Loney",
    "Kitty Katz",
    "Tom Katz",
    "Bud Light",
    "Bud Wiser",
    "C. Good",
    "C. Senor",
    "C. Worthy",
    "Cam Payne",
    "Carrie Oakey",
    "Chip Munk",
    "Chris Cross",
    "Chris P. Bacon",
    "Claire Annette Reed",
    "Count Dunn",
    "Count Orff",
    "Crystal Claire Waters",
    "D. Liver",
    "Dan D. Lyons",
    "Dan Druff",
    "Dick Bender",
    "Dick Pound",
    "Dick Handler",
    "Don Key",
    "Doris Schutt",
    "Dusty Carr",
    "Dusty Rhodes",
    "Earl E. Bird",
    "Earl Lee Riser",
    "Ernie Coli",
    "Estelle Hertz",
    "Faith Christian",
    "Ferris Wheeler",
    "Forrest Green",
    "Frank Enstein",
    "Gene Poole",
    "Harden Thicke",
    "Helen Back",
    "Hugh Jorgan",
    "Hugh Morris",
    "I.D. Clair",
    "I.M. Boring",
    "I.P. Freely",
    "I.P. Daly",
    "Iona Ford",
    "Iona Frisbee",
    "Iona Stonehouse",
    "Isadore Bell",
    "Ivy Leage",
    "Jack Goff",
    "Jack Haas",
    "Jacklyn Hyde",
    "Joe King",
    "Kenya Dewit",
    "Lou Pole",
    "Luke Warm",
    "M. Balmer",
    "Marshall Law",
    "Minny van Gogh, Br.",
    "Misty Waters",
    "Moe B. Dick",
    "Moe DeGrasse",
    "Noah Lott",
    "Olive Yew",
    "Ophelia Payne",
    "Paige Turner",
    "Pearl E. Gates",
    "Pepe Roni",
    "Phil Bowles",
    "Polly Ester",
    "Raney Schauer",
    "Rhoda Booke",
    "Rita Booke",
    "Rose Bush",
    "Russell Sprout",
    "Sal A. Mander",
    "Sharon Weed",
    "Sharon A. Burger",
    "Wanda Burger",
    "X. Benedict"
]
